### ISSUE TITLE
this would be better served from a gist

### ISSUE THREAD

**Issue by christopherlovell** [clemsonciti/singularity-in-jupyter-notebook#1]
https://gist.github.com/

**Comment by shwina** [comment]
Thanks, @christopherlovell - as far as I know, you can't create Gists under an organization. Perhaps this has changed?

**Comment by christopherlovell** [comment]
You're right, it's been on the todo list for over [four years](https://webapps.stackexchange.com/questions/11011/can-i-associate-a-github-gist-with-an-organization)
